### ISSUE TITLE
Invalid protocol message error if I try any command provided by this package

### ISSUE THREAD

**Issue by EGmux** [mmontone/slime-breakpoints#4]
emacs version:
 (GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0))

In the Emacs side I have this:

```
`(use-package slime
  :ensure t
  :after corfu
  :commands (slime))

(use-package slime-breakpoints
  :after slime
  :ensure (:host github :repo "mmontone/slime-breakpoints" :branch "master")
  :load-path "~/.emacs.d/elpaca/repos/elpaca/slime-breakpoints"
  :config
  (push "~/.emacs.d/elpaca/repos/elpaca/slime-breakpoints" load-path)
  (setq slime-contribs '(slime-fancy slime-breakpoints))
  (slime-setup))`

```
it works as expected, the command appear after pressing `M-x`, although no keybinds are provided.

In the SBCL side I have this

```
(require :swank)
(push #p"~/.emacs.d/elpaca/repos/slime-breakpoints/" swank::*load-path*)
```

but if I try any command, after a `edebug-defun` in the corresponding function I get this and without the edebug-defun call it hang Emacs indefinetly:

```
Invalid protocol message:
Package SLIME-BREAKPOINTS does not exist.

  Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "(:emacs-...">

(:emacs-rex (slime-breakpoints:list-of-breakpoints) "COMMON-LISP-USER" t 22)

```

**Comment by mmontone** [comment]
It seems the SWANK extension on Common Lisp side is not being loaded. I cannot tell why because I haven't used `use-package` for configuring SLIME.
